app_product_index:
    path: /products/
    methods: [GET, POST]
    controller: App\Controller\ProductController::index

app_product_show:
    path: /products/{slug}/
    methods: [GET, POST]
    controller: App\Controller\ProductController::show

