app_admin_product_index:
    path: /products/
    methods: [GET]
    controller: App\Controller\Admin\ProductController::index

app_admin_product_create:
    path: /products/create/
    methods: [GET, POST]
    controller: App\Controller\Admin\ProductController::create

app_admin_product_edit:
    path: /products/{id}/edit/
    methods: [GET, POST]
    controller: App\Controller\Admin\ProductController::edit
    requirements:
        id: \d+

app_admin_product_show:
    path: /products/{id}/show/
    methods: [GET, POST]
    controller: App\Controller\Admin\ProductController::show
    requirements:
        id: \d+

app_admin_product_delete:
    path: /products/{id}/delete/
    methods: [GET, DELETE]
    controller: App\Controller\Admin\ProductController::delete
    requirements:
        id: \d+
    options:
        expose: true

app_admin_product_bulk_delete:
    path: /products/bulk/delete/
    methods: [GET, DELETE]
    controller: App\Controller\Admin\ProductController::deleteBulk
    options:
        expose: true


