app_admin_tag_index:
    path: /tags/
    methods: [GET]
    controller: App\Controller\Admin\TagController::index

app_admin_tag_create:
    path: /tags/create/
    methods: [GET, POST]
    controller: App\Controller\Admin\TagController::create

app_admin_tag_edit:
    path: /tags/{id}/edit/
    methods: [GET, POST]
    controller: App\Controller\Admin\TagController::edit
    requirements:
        id: \d+

app_admin_tag_delete:
    path: /tags/{id}/delete/
    methods: [GET, DELETE]
    controller: App\Controller\Admin\TagController::delete
    requirements:
        id: \d+
    options:
        expose: true

app_admin_tag_bulk_delete:
    path: /tags/bulk/delete/
    methods: [GET, DELETE]
    controller: App\Controller\Admin\TagController::deleteBulk
    options:
        expose: true


