app_admin_tax_index:
    path: /taxes/
    methods: [GET]
    controller: App\Controller\Admin\TaxController::index

app_admin_tax_create:
    path: /taxes/create/
    methods: [GET, POST]
    controller: App\Controller\Admin\TaxController::create

app_admin_tax_edit:
    path: /taxes/{id}/edit/
    methods: [GET, POST]
    controller: App\Controller\Admin\TaxController::edit
    requirements:
        id: \d+

app_admin_tax_delete:
    path: /taxes/{id}/delete/
    methods: [GET, DELETE]
    controller: App\Controller\Admin\TaxController::delete
    requirements:
        id: \d+
    options:
        expose: true

app_admin_tax_bulk_delete:
    path: /taxes/bulk/delete/
    methods: [GET, DELETE]
    controller: App\Controller\Admin\TaxController::deleteBulk
    options:
        expose: true


